### ISSUE TITLE
MysqlDumpSplitSQL.py 有bug，执行卡住了

### ISSUE THREAD

**Issue by zeusYi** [ddcw/ddcw#2]
<img width="974" alt="image" src="https://github.com/ddcw/ddcw/assets/22519964/7110d990-0d9d-4002-82ec-4f4cda2a2afc">

<img width="1097" alt="image" src="https://github.com/ddcw/ddcw/assets/22519964/280a0213-1ac4-46ee-bf96-f21615e9a5f4">

导出命令：
mysqldump -h127.0.0.1 -uroot -pxxxx  --events --triggers --single-transaction --routines --master-data=2 -A > db.sql

拆分命令：
 python2 mysqldump_split.py  db.sql

版本:
Server version: 5.7.30-log MySQL Community Server (GPL)

**Comment by zeusYi** [comment]
<img width="783" alt="image" src="https://github.com/ddcw/ddcw/assets/22519964/68ca1338-e721-4f25-a875-5c6ce1f2a38e">

**Comment by ddcw** [comment]
> <img alt="image" width="974" src="https://private-user-images.githubusercontent.com/22519964/309187701-7110d990-0d9d-4002-82ec-4f4cda2a2afc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODA2MTgsIm5iZiI6MTcwOTI4MDMxOCwicGF0aCI6Ii8yMjUxOTk2NC8zMDkxODc3MDEtNzExMGQ5OTAtMGQ5ZC00MDAyLTgyZWMtNGY0Y2RhMmEyYWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMjBmZDk5MTNmNjZkODk5NThlMzY2OTI0ZjExMmRkNzMyMTY2OWY3ZGY5NDcxMTg3MzlhMWFhYmVmNDI3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOzjp_HrudADJ3J01HwbHKwvnRd3VNMYZBRZeYPSBIM"> <img alt="image" width="1097" src="https://private-user-images.githubusercontent.com/22519964/309187730-280a0213-1ac4-46ee-bf96-f21615e9a5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODA2MTgsIm5iZiI6MTcwOTI4MDMxOCwicGF0aCI6Ii8yMjUxOTk2NC8zMDkxODc3MzAtMjgwYTAyMTMtMWFjNC00NmVlLWJmOTYtZjIxNjE1ZTlhNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOThjOTE4MjcwMzhjMjc5MTg1MjAzNzM4NTBiOTE5NjY2NWIwZWZlZDhlYzA3YjQ1OWJjMWJjM2ExMmY0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fn4lOKwSvRPeKJkKM5hl7jkaty21zme0siZ7O2cmke8">
> 导出命令： mysqldump -h127.0.0.1 -uroot -pxxxx --events --triggers --single-transaction --routines --master-data=2 -A > db.sql
> 
> 拆分命令： python2 mysqldump_split.py db.sql
> 
> 版本: Server version: 5.7.30-log MySQL Community Server (GPL)

抱歉, 没有考虑到存储过程在结尾但又为空的时候, 已经修复. 请下载最新版, 再试下呢.
```python
                        elif data[:6] == "SET @@": #issue 2
                                break

```

**Comment by zeusYi** [comment]
--database参数有问题

<img width="1134" alt="image" src="https://github.com/ddcw/ddcw/assets/22519964/9aeb1881-5e50-4a46-a172-ab25b04cc551">


指定导出--database testdb2

但是testdb也导出了

**Comment by ddcw** [comment]
> --database参数有问题
> 
> <img alt="image" width="1134" src="https://private-user-images.githubusercontent.com/22519964/309208633-9aeb1881-5e50-4a46-a172-ab25b04cc551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODQ5ODUsIm5iZiI6MTcwOTI4NDY4NSwicGF0aCI6Ii8yMjUxOTk2NC8zMDkyMDg2MzMtOWFlYjE4ODEtNWU1MC00YTQ2LWExNzItYWIyNWIwNGNjNTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWQ5ODg0OTUwM2U5OTZiYWI1MWJjYWY3ZWMzNzBmOWQxMGVhZWE1YTJhZmUxMWY1YWQxMzMzYWU1ZDRjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXVMPrlSfsuGcKUME1skyRCyrYuhHKESUXKd4D8sH28">
> 指定导出--database testdb2
> 
> 但是testdb也导出了

只是显示导出来了, 而且也会存在该.sql文件, 但是里面**内容是空**的. 
`--database` 功能是后面加的, 但是又不想改动太多代码, 就设计成这样了.
你可以把那些 大小为0 的文件都找出来, 然后删掉`find splitByddcw_20240301_172448 -size 0 -name "*.sql" | xargs -t -i rm {}`
也可以在`read_table`函数结尾添加个逻辑判断, 如果为空就删除该文件.

这是**特性**

**Comment by zeusYi** [comment]
<img width="1175" alt="image" src="https://github.com/ddcw/ddcw/assets/22519964/b113f9fd-1a95-46e2-9697-84575b346052">

**Comment by ddcw** [comment]
> <img alt="image" width="1175" src="https://private-user-images.githubusercontent.com/22519964/309212685-b113f9fd-1a95-46e2-9697-84575b346052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODU4MzMsIm5iZiI6MTcwOTI4NTUzMywicGF0aCI6Ii8yMjUxOTk2NC8zMDkyMTI2ODUtYjExM2Y5ZmQtMWE5NS00NmUyLTk2OTctODQ1NzViMzQ2MDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZGZhMWQ1NmM1NTFjZTkxMjNjMzVlODExMDZmZDhlODdkODc5Y2M3NWUzMTQzYzc1YThhYzk5Njk2NjFlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hO2CpaNq8ScBejkHKhuhmBXOrnBPWFpMg8win8SHcaY">

目前的库表匹配能力较弱,
如果要匹配 testdb.t1 表, 需要使用 `--database testdb --table t1` 
当然支持正则表达式, 比如匹配db1.t1开头的表 就可以使用 `--database db1 --table "t1*"`
注: 加引号的目的是防止*被shell解析了

**Comment by zeusYi** [comment]
好的
